default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: admin1
  password: admin
  pool: 5

development:
  <<: *default
  database: development


test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  database: yendo_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)