default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: development


test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  database: yendo_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)