# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Category.create!([{name: "Helados"}, {name: "Hamburgueserías"}, {name: "Café"},
    {name: "Pizzerías"}, {name: "Vegetariano"}])

Store.create!([{name: "Freddo", category_id: 1, url: 'locales/freddo.png', ratings:[1,1,1,2]},
  {name: "Daniel", category_id: 1, url: 'locales/daniel.png', ratings:[4,5,4,4]},
  {name: "Lucciano's", category_id: 1, url: 'locales/luccianos.png', ratings:[5,5,4,3,3]},
  {name: "McDonalds", category_id: 2, url: 'locales/mc.png', ratings:[3,3,3,4]},
  {name: "Burguer King", category_id: 2, url: 'locales/burguerking.png', ratings:[3,4,3,4]},
  {name: "Mostaza", category_id: 2, url: 'locales/mostaza.png', ratings:[4,4,4]},
  {name: "Starbucks", category_id: 3, url: 'locales/starbucks.png', ratings:[5,4,5,4]},
  {name: "Café Martinez", category_id: 3, url: 'locales/cafemartinez.png', ratings:[3,4,5,2]},
  {name: "Café Registrado", category_id: 3, url: 'locales/caferegistrado.png', ratings:[5,5,5,4]},
  {name: "Hells Pizza", category_id: 4, url: 'locales/hellspizza.png', ratings:[3,3,5,3,2,4]},
  {name: "La Continental", category_id: 4, url: 'locales/lacontinental.png', ratings:[1,1,5,3,2,4]},
  {name: "La Farola", category_id: 4, url: 'locales/lafarola.png', ratings:[3,3,4]},
  {name: "Veggie Life", category_id: 5, url: 'locales/veggielife.png', ratings:[5,5,5,5,1]},
  {name: "Ave Caesar", category_id: 5, url: 'locales/ave.png', ratings:[5,4,4,5,2]},
  {name: "Green Eat", category_id: 5, url: 'locales/greeneat.png', ratings:[5,5,4,3,2,3,3]}])
  
Location.create!([{street: "Av. Cabildo 2569, CABA", store_id: 1},
    {street: "Av. del Libertador 7112, CABA", store_id: 2}, 
    {street: "Av. Melián 4602, CABA", store_id: 3}, 
    {street: "Av. Corrientes 1502, CABA", store_id: 4}, 
    {street: "Av. Monroe 3548, CABA", store_id: 5},
    {street: "Av. Corrientes 3247, CABA", store_id:6},
    {street: "Av. Entre Rios 415, CABA", store_id:7},
    {street: "Av. del Libertador 3883, CABA", store_id:8},
    {street: "Av. Alvarez Thomas 1502, CABA", store_id:9},
    {street: "Av. Córdoba 4302, CABA", store_id:10},
    {street: "Av. Rivadavia 4668, CABA", store_id:11},
    {street: "Av. Cabildo 1721, CABA", store_id:12},
    {street: "Av. Córdoba 4302, CABA", store_id:13},
    {street: "Quevedo 3365, CABA", store_id:14},
    {street: "Cuenca 3234, CABA", store_id:15}])

Food.create!([{name: "Cucurucho", price: 550, store_id: 1, url: 'foods/cucurucho.png'}, 
 {name: "Cucurucho", price: 550, store_id: 2, url: 'foods/cucurucho.png'},
 {name: "Cucurucho", price: 550, store_id: 3, url: 'foods/cucurucho.png'},
 {name: "1 Kg de Helado", price: 3500, store_id: 1, url: 'foods/potehelado.png'},
 {name: "1 Kg de Helado", price: 3500, store_id: 2, url: 'foods/potehelado.png'},
 {name: "1 Kg de Helado", price: 3500, store_id: 3, url: 'foods/potehelado.png'},
 {name: "1/2 Kg de Helado", price: 2000, store_id: 1, url: 'foods/mediohelado.png'},
 {name: "1/2 Kg de Helado", price: 2000, store_id: 2, url: 'foods/mediohelado.png'},
 {name: "1/2 Kg de Helado", price: 2000, store_id: 3, url: 'foods/mediohelado.png'},
 {name: "1/4 Kg de Helado", price: 1000, store_id: 1, url: 'foods/cuartohelado.png'},
 {name: "1/4 Kg de Helado", price: 1000, store_id: 2, url: 'foods/cuartohelado.png'},
 {name: "1/4 Kg de Helado", price: 1000, store_id: 3, url: 'foods/cuartohelado.png'},
 {name: "Palito Bombón", price: 450, store_id: 1, url:'foods/palito.png'},
 {name: "Palito Bombón", price: 450, store_id: 2, url:'foods/palito.png'},
 {name: "Palito Bombón", price: 450, store_id: 3, url:'foods/palito.png'},
 {name: "Palito de agua", price: 350, store_id: 1, url:'foods/palitoagua.png'},
 {name: "Palito de agua", price: 350, store_id: 2, url:'foods/palitoagua.png'},
 {name: "Palito de agua", price: 350, store_id: 3, url:'foods/palitoagua.png'},
 {name: "Bombón Suizo x 6", price: 3500, store_id: 1, url:'foods/suizo.png'},
 {name: "Bombón Suizo x 6", price: 3500, store_id: 2, url:'foods/suizo.png'},
 {name: "Bombón Suizo x 6", price: 3500, store_id: 3, url:'foods/suizo.png'},
 {name: "Bombón Escocés x 6", price: 3500, store_id: 1, url:'foods/escoces.png'},
 {name: "Bombón Escocés x 6", price: 3500, store_id: 2, url:'foods/escoces.png'},
 {name: "Bombón Escocés x 6", price: 3500, store_id: 3, url:'foods/escoces.png'},
 {name: "Torta Helada", price: 3600, store_id: 1, url:'foods/helada.png'},
 {name: "Torta Helada", price: 3600, store_id: 2, url:'foods/helada.png'},
 {name: "Torta Helada", price: 3600, store_id: 3, url:'foods/helada.png'},
 {name: "Tableta de Chocolate", price: 350, store_id: 1, url:'foods/americana.jpg'},
 {name: "Tableta de Chocolate", price: 350, store_id: 2, url:'foods/americana.jpg'},
 {name: "Tableta de Chocolate", price: 350, store_id: 3, url:'foods/americana.jpg'},
 {name: "Tableta de Dulce de Leche", price: 350, store_id: 1, url:'foods/ddl.jpg'},
 {name: "Tableta de Dulce de Leche", price: 350, store_id: 2, url:'foods/ddl.jpg'},
 {name: "Tableta de Dulce de Leche", price: 350, store_id: 3, url:'foods/ddl.jpg'},
 {name: "Tableta de Frutilla", price: 350, store_id: 1, url:'foods/frutilla.jpg'},
 {name: "Tableta de Frutilla", price: 350, store_id: 2, url:'foods/frutilla.jpg'},
 {name: "Tableta de Frutilla", price: 350, store_id: 3, url:'foods/frutilla.jpg'},
 {name: "Hamburguesa con queso", price: 1500, store_id: 4, url:'foods/queso.png'}, 
 {name: "Hamburguesa con queso", price: 1500, store_id: 5, url:'foods/queso.png'},
 {name: "Hamburguesa con queso", price: 1500, store_id: 6, url:'foods/queso.png'},
 {name: "Doble cuarto", price: 2600, store_id: 4, url:'foods/doble.png'},
 {name: "Doble cuarto", price: 2600, store_id: 5, url:'foods/doble.png'},
 {name: "Doble cuarto", price: 2600, store_id: 6, url:'foods/doble.png'},
 {name: "Cuarto de Libra", price: 2200, store_id: 4, url:'foods/cuarto.png'},
 {name: "Cuarto de Libra", price: 2200, store_id: 5, url:'foods/cuarto.png'},
 {name: "Cuarto de Libra", price: 2200, store_id: 6, url:'foods/cuarto.png'},
 {name: "Sandwich de Pollo", price: 2100, store_id: 4, url:'foods/mcpollo.png'},
 {name: "Sandwich de Pollo", price: 2100, store_id: 5, url:'foods/mcpollo.png'},
 {name: "Sandwich de Pollo", price: 2100, store_id: 6, url:'foods/mcpollo.png'},
 {name: "Hamburguesa triple", price: 1950, store_id: 4, url:'foods/triple.png'},
 {name: "Hamburguesa triple", price: 1950, store_id: 5, url:'foods/triple.png'},
 {name: "Hamburguesa triple", price: 1950, store_id: 6, url:'foods/triple.png'},
 {name: "Nuggets x 20", price: 2800, store_id: 4, url:'foods/nuggets.png'},
 {name: "Nuggets x 20", price: 2800, store_id: 5, url:'foods/nuggets.png'},
 {name: "Nuggets x 20", price: 2800, store_id: 6, url:'foods/nuggets.png'},
 {name: "Hamburguesa con Bacon", price: 2700, store_id: 4, url:'foods/bacon.png'},
 {name: "Hamburguesa con Bacon", price: 2700, store_id: 5, url:'foods/bacon.png'},
 {name: "Hamburguesa con Bacon", price: 2700, store_id: 6, url:'foods/bacon.png'},
 {name: "Papas fritas", price: 570, store_id: 4, url:'foods/papas.png'},
 {name: "Papas fritas", price: 570, store_id: 5, url:'foods/papas.png'},
 {name: "Papas fritas", price: 570, store_id: 6, url:'foods/papas.png'},
 {name: "Sundae", price: 750, store_id: 4, url:'foods/sundae.png'},
 {name: "Sundae", price: 750, store_id: 5, url:'foods/sundae.png'},
 {name: "Sundae", price: 750, store_id: 6, url:'foods/sundae.png'},
 {name: "Gaseosa", price: 450, store_id: 4, url:'foods/coca.png'},
 {name: "Gaseosa", price: 450, store_id: 5, url:'foods/coca.png'},
 {name: "Gaseosa", price: 450, store_id: 6, url:'foods/coca.png'},
 {name: "Agua sin gas", price: 400, store_id: 4, url:'foods/agua.png'},
 {name: "Agua sin gas", price: 400, store_id: 5, url:'foods/agua.png'},
 {name: "Agua sin gas", price: 400, store_id: 6, url:'foods/agua.png'},
 {name: "Latte", price: 750, store_id: 7, url:'foods/latte.png'}, 
 {name: "Latte", price: 750, store_id: 8, url:'foods/latte.png'}, 
 {name: "Latte", price: 750, store_id: 9, url:'foods/latte.png'}, 
 {name: "Capuchino", price: 800, store_id: 7, url:'foods/capu.png'}, 
 {name: "Capuchino", price: 800, store_id: 8, url:'foods/capu.png'}, 
 {name: "Capuchino", price: 800, store_id: 9, url:'foods/capu.png'}, 
 {name: "Café negro", price: 400, store_id: 7, url:'foods/cafe.png'},
 {name: "Café negro", price: 400, store_id: 8, url:'foods/cafe.png'},
 {name: "Café negro", price: 400, store_id: 9, url:'foods/cafe.png'}, 
 {name: "Café con leche", price: 550, store_id: 7, url:'foods/cafeconleche.png'},
 {name: "Café con leche", price: 550, store_id: 8, url:'foods/cafeconleche.png'},
 {name: "Café con leche", price: 550, store_id: 9, url:'foods/cafeconleche.png'},
 {name: "Submarino", price: 850, store_id: 7, url:'foods/submarino.png'}, 
 {name: "Submarino", price: 850, store_id: 8, url:'foods/submarino.png'}, 
 {name: "Submarino", price: 850, store_id: 9, url:'foods/submarino.png'}, 
 {name: "Flat White", price: 750, store_id: 7, url:'foods/flat.png'}, 
 {name: "Flat White", price: 750, store_id: 8, url:'foods/flat.png'}, 
 {name: "Flat White", price: 750, store_id: 9, url:'foods/flat.png'}, 
 {name: "Medialunas x 3", price: 600, store_id: 7, url:'foods/medialuna.png'},
 {name: "Medialunas x 3", price: 600, store_id: 8, url:'foods/medialuna.png'},
 {name: "Medialunas x 3", price: 600, store_id: 9, url:'foods/medialuna.png'},
 {name: "Alfajor de Dulce de Leche", price: 450, store_id: 7, url:'foods/alfajor.png'},
 {name: "Alfajor de Dulce de Leche", price: 450, store_id: 8, url:'foods/alfajor.png'},
 {name: "Alfajor de Dulce de Leche", price: 450, store_id: 9, url:'foods/alfajor.png'},
 {name: "Brownie", price: 820, store_id: 7, url:'foods/brownie.png'}, 
 {name: "Brownie", price: 820, store_id: 8, url:'foods/brownie.png'}, 
 {name: "Brownie", price: 820, store_id: 9, url:'foods/brownie.png'}, 
 {name: "Tostado", price: 1100, store_id: 7, url:'foods/tostado.png'}, 
 {name: "Tostado", price: 1100, store_id: 8, url:'foods/tostado.png'}, 
 {name: "Tostado", price: 1100, store_id: 9, url:'foods/tostado.png'}, 
 {name: "Napolitana", price: 2500, store_id: 10, url:'foods/napo.png'},
 {name: "Napolitana", price: 2500, store_id: 11, url:'foods/napo.png'},
 {name: "Napolitana", price: 2500, store_id: 12, url:'foods/napo.png'}, 
 {name: "Empanada de carne", price: 550, store_id: 10, url:'foods/empanada.png'}, 
 {name: "Empanada de carne", price: 550, store_id: 11, url:'foods/empanada.png'}, 
 {name: "Empanada de carne", price: 550, store_id: 12, url:'foods/empanada.png'}, 
 {name: "Mozzarella", price: 2000, store_id: 10, url:'foods/mozza.png'}, 
 {name: "Mozzarella", price: 2000, store_id: 11, url:'foods/mozza.png'}, 
 {name: "Mozzarella", price: 2000, store_id: 12, url:'foods/mozza.png'}, 
 {name: "Jamón y Morrones", price: 3000, store_id: 10, url:'foods/morron.jpg'}, 
 {name: "Jamón y Morrones", price: 3000, store_id: 11, url:'foods/morron.jpg'},
 {name: "Jamón y Morrones", price: 3000, store_id: 12, url:'foods/morron.jpg'},
 {name: "Fugazzetta", price: 3500, store_id: 10, url:'foods/fuga.jpg'}, 
 {name: "Fugazzetta", price: 3500, store_id: 11, url:'foods/fuga.jpg'},
 {name: "Fugazzetta", price: 3500, store_id: 12, url:'foods/fuga.jpg'},
 {name: "Anchoas", price: 2700, store_id: 10, url:'foods/anchoas.png'}, 
 {name: "Anchoas", price: 2700, store_id: 11, url:'foods/anchoas.png'}, 
 {name: "Anchoas", price: 2700, store_id: 12, url:'foods/anchoas.png'}, 
 {name: "Calabresa", price: 4000, store_id: 10, url:'foods/calabresa.jpg'}, 
 {name: "Calabresa", price: 4000, store_id: 11, url:'foods/calabresa.jpg'}, 
 {name: "Calabresa", price: 4000, store_id: 12, url:'foods/calabresa.jpg'}, 
 {name: "Provolone", price: 3300, store_id: 10, url:'foods/provo.png'}, 
 {name: "Provolone", price: 3300, store_id: 11, url:'foods/provo.png'}, 
 {name: "Provolone", price: 3300, store_id: 12, url:'foods/provo.png'}, 
 {name: "Jamón Crudo y Rúcula", price: 4100, store_id: 10, url:'foods/rucu.png'}, 
 {name: "Jamón Crudo y Rúcula", price: 4100, store_id: 11, url:'foods/rucu.png'}, 
 {name: "Jamón Crudo y Rúcula", price: 4100, store_id: 12, url:'foods/rucu.png'}, 
 {name: "Jamón y Huevo", price: 2900, store_id: 10, url:'foods/huevo.png'}, 
 {name: "Jamón y Huevo", price: 2900, store_id: 11, url:'foods/huevo.png'}, 
 {name: "Jamón y Huevo", price: 2900, store_id: 12, url:'foods/huevo.png'}, 
 {name: "Wrap", price: 500, store_id: 13, url:'foods/wrap.jpg'}, 
 {name: "Wrap", price: 500, store_id: 14, url:'foods/wrap.jpg'},
 {name: "Wrap", price: 500, store_id: 15, url:'foods/wrap.jpg'},
 {name: "Ensalada", price: 700, store_id: 13, url:'foods/ensalada.png'},
 {name: "Ensalada", price: 700, store_id: 14, url:'foods/ensalada.png'},
 {name: "Ensalada", price: 700, store_id: 15, url:'foods/ensalada.png'},
 {name: "Veggie Burguer", price: 1100, store_id: 13, url:'foods/veggieburguer.png'},
 {name: "Veggie Burguer", price: 1100, store_id: 14, url:'foods/veggieburguer.png'},
 {name: "Veggie Burguer", price: 1100, store_id: 15, url:'foods/veggieburguer.png'},
 {name: "Wok Vegetariano", price: 1200, store_id: 13, url:'foods/wok.png'},
 {name: "Wok Vegetariano", price: 1200, store_id: 14, url:'foods/wok.png'},
 {name: "Wok Vegetariano", price: 1200, store_id: 15, url:'foods/wok.png'},
 {name: "Tarta de Puerro", price: 850, store_id: 13, url:'foods/puerro.png'},
 {name: "Tarta de Puerro", price: 850, store_id: 14, url:'foods/puerro.png'},
 {name: "Tarta de Puerro", price: 850, store_id: 15, url:'foods/puerro.png'},
 {name: "Tarta de Calabaza", price: 700, store_id: 13,  url:'foods/calabaza.jpg'},
 {name: "Tarta de Calabaza", price: 700, store_id: 14,  url:'foods/calabaza.jpg'},
 {name: "Tarta de Calabaza", price: 700, store_id: 15,  url:'foods/calabaza.jpg'},
 {name: "Berenjeas Gratinadas", price: 1700, store_id: 13, url:'foods/berenjena.png'},
 {name: "Berenjeas Gratinadas", price: 1700, store_id: 14, url:'foods/berenjena.png'},
 {name: "Berenjeas Gratinadas", price: 1700, store_id: 15, url:'foods/berenjena.png'},
 {name: "Muffin de Zanahoria", price: 700, store_id: 13, url:'foods/muffin.png'},
 {name: "Muffin de Zanahoria", price: 700, store_id: 14, url:'foods/muffin.png'},
 {name: "Muffin de Zanahoria", price: 700, store_id: 15, url:'foods/muffin.png'},
 {name: "Empanada de Verdura", price: 300, store_id: 13, url:'foods/verdura.jpg'},
 {name: "Empanada de Verdura", price: 300, store_id: 14, url:'foods/verdura.jpg'},
 {name: "Empanada de Verdura", price: 300, store_id: 15, url:'foods/verdura.jpg'},
 ])

